name: Deploy Terraform en LocalStack

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LOCALSTACK_API_KEY: ""   # Fuerza modo gratuito
      LOCALSTACK_AUTH_TOKEN: ""                       # Evita modo PRO
      LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENTS: "1" # Acepta modo FREE

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Instalar LocalStack CLI
        run: pip install localstack

      - name: Iniciar LocalStack en background
        run: localstack start -d

      - name: Esperar a que LocalStack esté listo
        run: |
          echo "Esperando LocalStack..."
          localstack wait -t 30

      - name: Inicializar Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Aplicar Terraform (auto-approve)
        run: terraform apply -auto-approve

